name: aster
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - tqdm
  - jupyter
  - notebook
  - ipywidgets
  - ipykernel
  - openpyxl
  - pip
  - faiss-cpu
 - pip:
    - kaggle
    - streamlit
    - langchain
    - langchain-community  
    - langchain-openai
    - openai
    - python-dotenv
    - pypdf